version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # зробив спеціальну застримку що б при запуску контейнера база даних була готова до роботи, і не виникало помилки "could not connect to server: Connection refused"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/contacts_db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
